### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by iamareebjamal** [zhcet-amu/zhcet-web#98]
- [x] Test the whole application
- [x] Replace email to official one
- [x] Create production and development properties
- [x] Remove official keys from deployments
